name: Test Preflight Checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-preflight-checks:
    uses: ./.github/workflows/qcom-preflight-checks-reusable-workflow.yml
    with:
      repolinter: true
      semgrep: true
      copyright-license-detector: true
      pr-check-emails: true
      dependency-review: true
